### PR TITLE
Release/meh

### PR DESCRIPTION
**Pull request by sabi1981**

### CODE REVIEW

**Comment by splatEric** [comment]
I don't have any problem with this being merged in, but would prefer @biskyt to review and confirm as I don't have any real oversight of what's going on with the functionality in the meh releases

**Comment by biskyt** [comment]
Tested. I get the following error whenever I try to go to the genetics screen. E.g, http://demo.abehrdigital.com/Genetics/subject/edit?patient=19573

```
PHP notice

Undefined variable: callback

/var/www/openeyes/protected/views/disorder/disorderAutoComplete.php(8)

01 <script type="text/javascript">
02   $(document).ready(function() {
03     $('#enteredDiagnosisText').on('click', '.clear-diagnosis-widget', function (e) {
04       e.preventDefault();
05       $('.multiDiagnosis[value="' + $(this).data('diagnosisId') +'"').remove();
06       $('input[id=savedDiagnosis]').val('');
07       $(this).parent().hide();
08       <?= $callback ? $callback . '();' : '' ?>
09     });
10   });
11   var source = function(request, response) {
12     $.ajax({
13       'url': '<?=Yii::app()->createUrl('/disorder/autocomplete')?>',
14       'type':'GET',
15       'data':{'term': request.term, 'code': "<?=$code?>"},
16       'success':function(data) {
17         data = $.parseJSON(data);
18         response(data);
19       }
20     });
```

This may require something additional in the V2.0 code?

**Comment by biskyt** [comment]
Actually, I get the same error on http://demo.abehrdigital.com too, which doesn't have this code merged in. So probably irrelevant to this pull request. I'll carry on testing the other bits...

**Comment by biskyt** [comment]
OK. Other than the above mentioned (pre-existing) issue, I have not found any other problems with genetics modules or correspondence (which is all that should be affected)

**Pull request merged**
