### PR TITLE
Vagrant + Ansible based development environment

### PR DESCRIPTION
**Pull request by davidfsmith**
Changes to switch the build of the development environment to use Vagrant + Ansible.  This is designed to simplify the build of the development environment and ensure consistency.

The build steps are based upon the work of both [OE_installer](http://github.com/openeyes/oe_installer) and also the previous Puppet based install and creates a fully working Virtualbox or VMWare Fusion based development environment complete with database load and migrations as required.

Todo:
* Fully test on Windows
* Ensure that tests are able to run

### CODE REVIEW

**Comment by splatEric** [comment]
Am going to do a clone and build as a sanity test ... but in principle I'm happy to go ahead with this.

**Comment by davidfsmith** [comment]
The Vagrantfile has been updated to allow the passing in of an optional hostname and servername. @splatEric

**Comment by davidfsmith** [comment]
@splatEric can you test the latest changes please as I'd like to get this merged in

**Comment by splatEric** [comment]
seems to work well for bringing up a devbox on my machine. Run a test with a specified hostname and all worked as expected.

**Pull request merged**
